services:
  splunk:
    image: splunk/splunk:latest
    ports:
      - "8342:8000"
      - "8088:8088"
      - "8089:8089"
    environment:
      SPLUNK_GENERAL_TERMS: --accept-sgt-current-at-splunk-com
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_PASSWORD: Password123!

  monitoring-service:
    build: ./monitoring-service
    ports:
      - "8002:8002"
    environment:
      SPLUNK_HEC_URL: ${SPLUNK_HEC_URL}
      SPLUNK_TOKEN: ${SPLUNK_TOKEN}
    depends_on:
      - splunk

  web-app:
    build: ./web-app
    ports:
      - "8001:8001"
    environment:
      MONITORING_SERVICE_URL: http://monitoring-service:8002
      WEB_APP_URL: http://127.0.0.1:8001
      ENABLE_LOAD_GENERATOR: ${ENABLE_LOAD_GENERATOR:-true}
    depends_on:
      - monitoring-service

  dashboard:
    build: ./dashboard
    ports:
      - "8003:8003"
    environment:
      SPLUNK_URL: ${SPLUNK_URL:-https://splunk:8089}
      SPLUNK_USER: ${SPLUNK_USER:-admin}
      SPLUNK_PASSWORD: ${SPLUNK_PASSWORD:-Password123!}
    depends_on:
      - splunk
